version: 2
updates:
  # Python (backend)
  - package-ecosystem: "pip"
    directory: "/"          # requirements.txt лежит в корне
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Node.js (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"  # папка с package.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
