apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-minio-credentials
  namespace: default
type: Opaque
stringData:
  # Те же значения, что MINIO_ROOT_USER / MINIO_ROOT_PASSWORD
  # или сделай отдельного пользователя в MinIO, если захочешь.
  ACCESS_KEY_ID: pyro-minio
  ACCESS_SECRET_KEY: H2&h2&h2&1
