apiVersion: v1
kind: Secret
metadata:
  name: gigachat-secrets
  namespace: default
type: Opaque
stringData:
  # Твой ключ авторизации GigaChat (без "Bearer ", просто сам ключ)
  GIGACHAT_CREDENTIALS: "YWE2YmQ2MzAtYmEwZS00MjhjLWI3ODgtYjZiMDMwMzI0OGZhOjQxNmY0OThiLTA2YTYtNDU5OS1iZWQ4LWVhZjZlMWI3MTU0OA=="
  # Если нужно отключить проверку SSL (иногда нужно для российских сертификатов)
  GIGACHAT_VERIFY_SSL: "false"