apiVersion: v1
kind: Secret
metadata:
  name: minio-root-credentials
  namespace: default
type: Opaque
stringData:
  # ЗАДАЙ свои логин/пароль, не оставляй эти по умолчанию
  MINIO_ROOT_USER: pyro-minio
  MINIO_ROOT_PASSWORD: H2&h2&h2&1
