apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-pyro-db-internal
  namespace: default
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: pyro-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: pyro-db
      ports:
        - protocol: TCP
          port: 8000
