apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pyro-db-backup-secrets
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    # Разрешаем доступ только к одному секрету с кредами для MinIO
    resourceNames: ["cnpg-backup-minio-credentials"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pyro-db-backup-secrets-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pyro-db
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pyro-db-backup-secrets
