apiVersion: v1
kind: Service
metadata:
  name: pyro-api
  namespace: default
  labels:
    app: pyro-api
spec:
  type: ClusterIP
  selector:
    app: pyro-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
