jobs:
  scan:
    runs-on: ubuntu-latest

    # ✅ ENV на всю job (доступно во всех шагах)
    env:
      DATABASE_URL: sqlite+aiosqlite:///./test.db

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx aiosqlite

      - name: Tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=app --cov-report=xml:coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Quality Gate (fail on red)
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
